default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

  
development:
  <<: *default
  database: iachei_app_development


test:
  <<: *default
  database: iachei_app_test


production:
  <<: *default
  database: iachei_app_production
  username: iachei_app
  password: <%= ENV['IACHEI_APP_DATABASE_PASSWORD'] %>
